feat(linter/no-unresolved): inform on missing file vs directory imports (#210)
Add a label telling users if they're importing a missing file or a
directory.

```
  𝙭 no-unresolved: Unresolved import to 'does-not-exist.zig'
   ╭─[src/no-unresolved.zig:1:19]
 1 │ const x = @import("does-not-exist.zig");
   ·                   ───────────┬───────────
   ·                              ╰── file 'does-not-exist.zig' does not exist
   ╰────

```